### ISSUE TITLE
Connection refused when using WireGuard

### ISSUE THREAD

**Issue by 8ware** [duckduckgo/Android#887]
**Description**
When a WireGuard connection is active opening (an arbitrary) URLs always result in `net::ERR_CONNECTION_REFUSED`; works in Firefox, though.

**How to Reproduce**
1. Setup a WireGuard server, e. g. using docker-compose
    ```yaml
    version: "2.1"
    services:
      wireguard:
        image: linuxserver/wireguard:1.0.20200513-118.04-ls12
        container_name: wireguard
        cap_add:
          - NET_ADMIN
          - SYS_MODULE
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/Berlin
          - SERVERURL=<your-local-host> #optional
          - PEERS=1
        volumes:
          - ./config:/config
          - /lib/modules:/lib/modules:ro
          - /usr/src:/usr/src:ro
        ports:
          - 51820:51820/udp
        sysctls:
          - net.ipv4.conf.all.src_valid_mark=1
        restart: unless-stopped
    ```
    (see https://github.com/linuxserver/docker-wireguard for more information)
2. Install the WireGuard app (e. g. from F-Droid), scan the QR code (see `docker-compose logs`) and activate the tunnel
3. Go to https://github.com
4. See error `net::ERR_CONNECTION_REFUSED`
    ![image](https://user-images.githubusercontent.com/1367048/87207929-6f72b100-c30d-11ea-8c1e-d5f3e9b84e24.png)

**Expected behavior**
Site is opened as without WireGuard.

**Smartphone:**
 - DDG App Version: 5.55.1 (55501)
 - Device: – (ask if this information matters to you)
 - OS: Android 9 (Lineage OS)
